### PR TITLE
Added Organizations 

### PR DESCRIPTION
**Pull request by JoyBhalla**
Added organizations

### CODE REVIEW

**Comment by utkarsh2102** [comment]
@JoyBhalla, please update this ASAP. Also remove the merge conflict.

**Comment by JoyBhalla** [comment]
Done

**Comment by utkarsh2102** [comment]
LGTM.
If there persists a problem, we can push commits after the call.

**Comment by utkarsh2102** [comment]
Wait, publish your page and share the link here.

**Comment by JoyBhalla** [comment]
Link https://joybhalla.github.io/Pyladies-delhi-website/

**Comment by AniVerma17** [comment]
Requested changes:
- Change heading 'Organisations' to 'Organisers'.
- Replace dummy 'lorem ipsum' text with organisers' actual names if available (look into PyLadies' current site for this).

**Comment by vipulgupta2048** [comment]
@AniVerma17 @JoyBhalla As I mentioned previously on the call. PyLadies is **rebooting**. So how can the people be the same? and let's assume they are same. Wouldn't a more generalized approach help us later on if things are needed to be changed. We just need to make the **Structure**, images, content are their part. I don't understand even after repeating this so many times, why you both seem to have a hard time agreeing to it.

@utkarsh2102  Why was this PR closed, to begin with, and another one opened 60 minutes later. No wonder I get 20 emails from this repository alone.

**Comment by utkarsh2102** [comment]
He's got issues with Git/Github. He wasn't getting the expected responses even while pushing his commits. Hence, cloned over.

**Pull request closed without merging**
