### PR TITLE
[R2D] Website V2

### PR DESCRIPTION
**Pull request by thisisayush**
- Completely Themed Website
- Animations
- Responsive Menu
- Animated Preloader
- Transparent Logo
- Bug Fixes

Preview at: [github.thisisayush.com](https://github.thisisayush.com/Pyladies-delhi-website)

### CODE REVIEW

**Comment by thisisayush** [comment]
Add Smooth Page Scroll #22

**Comment by utkarsh2102** [comment]
The website is not loading :o

**Comment by utkarsh2102** [comment]
Is the space for other sponsors intentionally left or is it not aligned?

**Comment by AniVerma17** [comment]
Please shift up the logo image a bit to align its color boundaries with the inner sections.

**Comment by thisisayush** [comment]
> Please shift up the logo image a bit to align its color boundaries with the inner sections.
>> Can you elaborate? It seems fine on my side.

> Provide navigation links on the masthead also.
>> Need some more opinions on this. The upper part of the page seems empty, but it can contain upcoming events ticker as suggested by @vipulgupta2048 

> It would be better to place all the headings in the center.
>> The headlines are intentionally shifted to left or right positions according to the content which is shifted to the opposite side to give the design some meaning.

> Increase the opacity of description text in activities section for better readability.
>> Sure. This is a first draft, modifications shall be made in new PR's by more contributors :)

**Comment by AniVerma17** [comment]
screenshot from 2018-04-01 17-12-51
The lady image should be completely in the white area (as it is in the original logo), and color boundaries in the image and the sections should align with each other.

>The headlines are intentionally shifted to left or right positions according to the content which is shifted to the opposite side to give the design some meaning.
Then give the corresponding section content the same alignment as the heading, that will add meaning to the design as well as content.

**Comment by thisisayush** [comment]
> The lady image should be completely in the white area (as it is in the original logo), and color boundaries in the image and the sections should align with each other.
It's to give a design, I thought red from logo was leaking. Taking the image any up will cause the red colour from logo to leak in Mobile phones.

> Then give the corresponding section content the same alignment as the heading, that will add meaning to the design as well as content.
>> Sorry, didn't get it 😅

**Comment by AniVerma17** [comment]
>It's to give a design, I thought red from logo was leaking. Taking the image any up will cause the red colour from logo to leak in Mobile phones.

You can use media queries to solve this.

>Then give the corresponding section content the same alignment as the heading, that will add meaning to the design as well as content.
>>Sorry, didn't get it sweat_smile

**Comment by thisisayush** [comment]
> You can use media queries to solve this.
>> Only if I want to. It's a non-sarcastic case of "It's a feature, not a bug"

>For example, if heading of 'About' section is left aligned, then its content should also be left aligned. Such can be done with other sections also.
>> The zig-zag pattern is followed. If other people see a problem with it, go ahead and make the change, I don't mind :)

**Comment by thisisayush** [comment]
@vipulgupta2048 If anything minor needs to be added or modified, do tell me, wrna I'm marking it as complete from my end :+1:

**Comment by vipulgupta2048** [comment]
I was just reading the context of the conversation and following up on the developments of the PR. Since the site will take a leap, after this PR. I would like you to take a look at #22 of the features that I want to implement, give your views on it.  
@utkarsh2102 Is the site updated. Before this PR (Asking in reference to showing to Pushplata.)

**Comment by utkarsh2102** [comment]
Yes @vipulgupta2048. The site is updated till this PR (excluding this) and hosted at : https://utkarsh2102.github.io/Pyladies-delhi-website/
Also, your "Meetup" and "Submit Talks" section isn't aligned properly. So you might want to implement the required changes before showing to Pushplata.

**Comment by thisisayush** [comment]
@vipulgupta2048
I saw #22 it requires 404 and robots.txt, the site is static and I don't see a use case of either of them unless a web framework such as flask is used to route specific urls.

Also, what do you mean by API. What do you want to implement. Since, this PR states "redesigned Website", I'll not be implementing the same in this PR. Additional features shall be added on successive PRs after it's merged.

**Pull request merged**
