### PR TITLE
Added changes

### PR DESCRIPTION
**Pull request by JoyBhalla**
Changed Organisations to organisers and added names to the photos

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
Can you add a live demo of the same or some screenshot of the work done.

**Comment by JoyBhalla** [comment]
screenshot from 2018-03-30 21-33-27

**Comment by vipulgupta2048** [comment]
- There should be some space between organizers and the pictures to make it look cleaner. Also, see the extra space between the line email us and organizers. Please fix that.
- Consider removing these pictures and adding something dummy in their place (Suggestion)
- Also, make a placeholder for a 3rd picture.

**Comment by JoyBhalla** [comment]
On it

**Comment by JoyBhalla** [comment]
screenshot from 2018-03-30 21-59-03

Added:
Space b/w organisers and images
Placeholder images
Placeholder for 3rd picture

**Comment by JoyBhalla** [comment]
Let me know if you guys like it or not

**Comment by AniVerma17** [comment]
Reduce the gap between placeholder images and name texts.

**Comment by JoyBhalla** [comment]
Link https://joybhalla.github.io/Pyladies-delhi-website/

**Pull request merged**
