### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vips28**
Added my name as contributor in the file

### CODE REVIEW

**Comment by utkarsh2102** [comment]
Where's the loader and everything?
Am I simply suppose to merge a request with your name? :o 
@vipulgupta2048 & @AniVerma17?

**Comment by AniVerma17** [comment]
No... not until he has any merged contributions on the repo.

**Comment by utkarsh2102** [comment]
This PR will be closed soon. Take required actions @vips28.

**Comment by vipulgupta2048** [comment]
The preloader has been completed by @omkar10859 #17
Closing the PR.

**Pull request closed without merging**
