### PR TITLE
[Fix] Meetup Section Orientation

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Meetup section orientation is fixed. 
Thinking of changing colors too? Thoughts? [Give suggestions by Hex values]

### CODE REVIEW

**Comment by utkarsh2102** [comment]
Can you give a page preview?

**Comment by thisisayush** [comment]
[DO NOT MERGE] The structure for previous PR #28 is entirely different and will conflict if this one is merged. And honestly, I won't solve the conflicts. Already did once.

**Comment by akshat0047** [comment]
Probably a single merge conflict will arise due to addition which would be easily solved, we should merge the PR.

**Comment by thisisayush** [comment]
@vipulgupta2048 There will be at least 3 files which will conflict. It's not about 2 additions, but the whole source. You don't know where these additions will appear when #28  is merged.
Before merging this PR, do a test merge on a new branch.

**Comment by vipulgupta2048** [comment]
Good work @utkarsh2102 I was going to recommend you the same. Good that it works out for everyone.  
Closing this.

**Pull request closed without merging**
