### PR TITLE
Preloader added

### PR DESCRIPTION
**Pull request by omi10859**

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
@omi10859 Can you add a description of the work done on the preloader and a live demo of the same.

**Comment by omi10859** [comment]
Preloader add to website 
[demo here](https://omi10859.github.io/Pyladies-delhi-website/)

**Comment by vipulgupta2048** [comment]
@AniVerma17  @utkarsh2102 Any comments, LGTM to me

**Comment by AniVerma17** [comment]
Add some lazy loading to this, maybe a 1-1.5s timeout after page load for preloader to disappear.

**Comment by utkarsh2102** [comment]
Looks good now.

**Pull request merged**
