### PR TITLE
Darker Text

### LINKED ISSUE #33: Need dark text color.
Snapshot of present text color is as follows.
issue2
The text color in this section (and any other section where this color is used) is light and needs to be darkened in order to increase it's visibility.

### PR DESCRIPTION
**Pull request by thisisayush**
Fixes #33

### CODE REVIEW

**Comment by thisisayush** [comment]
Screenshot:

screenshot from 2018-06-02 16-43-06

**Comment by utkarsh2102** [comment]
@vipulgupta2048, please check the same.

**Comment by vipulgupta2048** [comment]
@thisisayush any updates?

**Comment by thisisayush** [comment]
Updated:
fireshot capture 5 - pyladies delhi chapter - http___localhost_8000_

**Pull request merged**
