### PR TITLE
[Fix] Header and Organisation section 

### PR DESCRIPTION
**Pull request by akshat0047**
added organisers in menu

added padding-top:150px to fix spawn

changed organisation header to organisers

### CODE REVIEW

**Comment by akshat0047** [comment]
demo- https://akshat0047.github.io/Pyladies-delhi-website/

**Comment by vipulgupta2048** [comment]
@akshat0047  Fix : Logo
Add a hyperlink to it, which reloads the website

**Comment by AniVerma17** [comment]
Modify the cursor for logo image to pointer type, to represent it as a link.

**Comment by utkarsh2102** [comment]
Up on clicking the icon, the site is not returning to the top. It's just reloading.
Shouldn't it jump to the top?

**Comment by utkarsh2102** [comment]
If I go towards the end, i.e. at "Contact Us" section and then click the logo for about 11 times, it then gradually leads to the top.
Funny observation, right? :o 
Please fix the same.

**Comment by AniVerma17** [comment]
Please remove the duplicated header and sections from the page.

**Comment by utkarsh2102** [comment]
@akshat0047, please check the page preview once. You'll get what you need to change.

**Comment by akshat0047** [comment]
The preview was normal when I made the request, even all of us have seen it, must be a merge which resulted in this conflict

**Comment by akshat0047** [comment]
Closing the PR due to change in the whole structure in #28

**Pull request closed without merging**
