### PR TITLE
FONT STYLE, HEADER LOGO, FONT COLOUR FIXED

### PR DESCRIPTION
**Pull request by akshat0047**
DEMO HERE:  
https://akshat0047.github.io/Pyladies-delhi-website/

FONT STYLE: 
The font of all descriptions is set to PT Sans Narrow, sans-serif, the same google font initialization is done

FONT COLOUR:
The font of about us and sponsor section is set to black colour

HEADER LOGO:
As per the requirement made the header logo is being set to 150px size which was initially 100px.

### CODE REVIEW

**Comment by AniVerma17** [comment]
Please increase the font size of about section by at least 0.1em to ensure better readability.

**Comment by utkarsh2102** [comment]
@AniVerma17, approve ASAP if it looks good.
LGTM. The icons are yet to be removed though.

**Comment by AniVerma17** [comment]
Font size is good now.
Approved.

**Comment by vipulgupta2048** [comment]
@akshat0047 BECAUSE SENTENCE CASE IS SO UNDERRATED, LET'S BREAK THE CAPS LOCK KEY AND WRITE LIKE THIS ALL DAY LONG. 

How do you feel about this? Any thoughts. I am not shouting, am I? Well, despite your best intentions, people would roast you on online forums if you use uppercase unnecessary. It is considered as shouting. Please take care, give your caps lock key some rest. 
@AniVerma17  YOU APPROVED THIS, LIKE THIS?
@thisisayush @utkarsh2102 @JoyBhalla Take note.

**Comment by AniVerma17** [comment]
@vipulgupta2048 I approved it for the code changes, chose to explain commenting practices for later because we all seem to be working against the clock.
Don't lose your cool on this.

**Comment by utkarsh2102** [comment]
Duly noted. Would be taken care of this is future.

**Pull request merged**
