### PR TITLE
Added Fork me on Github

### PR DESCRIPTION
**Pull request by omi10859**

### CODE REVIEW

**Comment by utkarsh2102** [comment]
@omi10859, please add a working demo link here.

**Comment by omi10859** [comment]
screen shot 2018-03-30 at 10 30 50 pm

**Comment by AniVerma17** [comment]
Looks good.

**Comment by omi10859** [comment]
screen shot 2018-03-30 at 10 42 37 pm

**Comment by omi10859** [comment]
Ready to get merged

**Comment by vipulgupta2048** [comment]
Don't merge, next PR will depreciate this :imp: 
I found something so much better.

**Pull request closed without merging**
