### PR TITLE
Improvements for V2

### PR DESCRIPTION
**Pull request by thisisayush**
- Add Horizontal Logo
- Add Attributions for Transparent Logo and Mouse SVG
- Remove Blogger and Facebook Links
- Add 'about' and 'organisers' to Menu
- Re-style Organisers Section
- Add Click To Scroll in Home
- Misc. Bug Fixes
  - Fix Smooth Scroll Top Offset
  - Add Missing Closed `<ul>` Tag
  - Improve Navbar Show Condition

Demo: https://github.thisisayush.com/Pyladies-delhi-website (May not be updated due to cache issues, do a `CTRL+F5` or empty cache)

### CODE REVIEW

**Comment by thisisayush** [comment]
@vipulgupta2048 Requested Changes have been done.

**Comment by vipulgupta2048** [comment]
Good work @thisisayush, I will get it reviewed again and will notify you of any changes that we need.

**Comment by vipulgupta2048** [comment]
@utkarsh2102  Well, I haven't received anything. If it was about fixing something, please mention it here. I am going to ping her again.

**Comment by utkarsh2102** [comment]
@vipulgupta2048, the issues have been opened for the same.
Also, if this looks good, shall I merge it?
Because the news issues have been opened and we might get unnecessary merge conflicts.

**Comment by utkarsh2102** [comment]
Why aren't the commits squashed?

**Comment by vipulgupta2048** [comment]
@thisisayush Do refer to the issues sections and get them resolved. ASAP.

**Comment by thisisayush** [comment]
@vipulgupta2048 Kindly merge this PR. Further changes will be submitted as separate PR's.

**Comment by utkarsh2102** [comment]
LGTM, merging.

**Pull request merged**
