### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by thisisayush**
Remove Gulp Installation Instructions.

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
I am already working on this

**Comment by thisisayush** [comment]
Oh Right. Didn't see that early. @vipulgupta2048

**Comment by vipulgupta2048** [comment]
Check it out, we collaborated on a commit. You don't see that every day do you.

**Comment by vipulgupta2048** [comment]
@AniVerma17 @utkarsh2102 @akshat0047 @joybhalla @vips28 Start commenting. Even if it is just an emoji to show approval.

**Comment by utkarsh2102** [comment]
LGTM!

**Pull request merged**
