### PR TITLE
NAVIGATION BAR, SPONSORS AND SECTION HEADINGS

### PR DESCRIPTION
**Pull request by akshat0047**
NAVIGATION BAR:
 Fixed menu icon, fixed menu opening bug on load of site, changed nav bar from fixed to sticky.

SPONSORS SECTION:
Added text content
Added background colour to email us link.

SECTION HEADINGS:
Changed background colour from none to rgba(255,68,68,0.9).
Changed font from default to- Lato , sans-serif.

### CODE REVIEW

**Comment by AniVerma17** [comment]
Please provide a preview for this (gh-pages).

**Comment by akshat0047** [comment]
DEMO HERE- https://akshat0047.github.io/pyladiespreview/

**Comment by vipulgupta2048** [comment]
Good Work @akshat0047  Can you make the logo at the top bigger (about 3x or 5x so that the Pyladies Delhi is visible. )

**Comment by utkarsh2102** [comment]
As discussed with @akshat0047, he'll make the above changes in his next PR.
Hence, merging it.

**Pull request merged**
